=== webhintio/hint/packages/sonarwhal/src/lib/config/config-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Configuration",
    "description": "A configuration file for sonarwhal",
    "type": "object",
    "properties": {
        "connector": {
            "description": "The connector to use to gather information",
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "The name of the connector to use",
                            "type": "string"
                        },
                        "options": {
                            "description": "The options to pass to the connector",
                            "type": "object"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "string"
                }
            ]
        },
        "extends": {
            "description": "Base configuration to use.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "formatters": {
            "description": "The formatter(s) to use for the results",
            "oneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "string"
                }
            ]
        },
        "parsers": {
            "description": "The parsers to be used with the connector to gather information for specific file types",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "rulesTimeout": {
            "description": "Time in milliseconds that a rule has to finish",
            "type": "number"
        },
        "rules": {
            "description": "The rules to validate",
            "anyOf": [
                {
                    "$ref": "#/definitions/ruleobject"
                },
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object"
                                    }
                                ],
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "minItems": 1
                }
            ],
            "minItems": 1,
            "uniqueItems": true
        },
        "browserslist": {
            "description": "The browsers supported",
            "anyOf": [
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true
                },
                {
                    "type": "string"
                }
            ]
        },
        "ignoredUrls": {
            "description": "The urls to ignore by the rules",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "domain": {
                        "type": "string",
                        "description": "Regex for the domain to ignore"
                    },
                    "rules": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "uniqueItems": true
                        }
                    }
                },
                "uniqueItems": true
            }
        }
    },
    "anyOf": [
        {
            "required": [
                "connector",
                "rules"
            ]
        },
        {
            "required": [
                "extends"
            ]
        }
    ],
    "additionalProperties": false,
    "definitions": {
        "errorlevelstring": {
            "type": "string",
            "enum": [
                "off",
                "warning",
                "error"
            ]
        },
        "errorlevelnumber": {
            "type": "number",
            "enum": [
                0,
                1,
                2
            ]
        },
        "ruleconfig": {
            "type": "array",
            "items": [
                {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/errorlevelstring"
                        },
                        {
                            "$ref": "#/definitions/errorlevelnumber"
                        }
                    ]
                },
                {
                    "type": "object"
                }
            ],
            "maxItems": 2,
            "minItems": 1,
            "uniqueItems": true
        },
        "ruleobject": {
            "type": "object",
            "patternProperties": {
                "^.+$": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/errorlevelstring"
                        },
                        {
                            "$ref": "#/definitions/errorlevelnumber"
                        },
                        {
                            "$ref": "#/definitions/ruleconfig"
                        }
                    ]
                }
            },
            "minItems": 1,
            "uniqueItems": true
        }
    }
}

=== webhintio/hint/packages/configuration-web-recommended/index.json
{
    "connector": {
        "name": "jsdom",
        "options": {
            "waitFor": 5000
        }
    },
    "formatters": [
        "summary"
    ],
    "rules": {
        "axe": "error",
        "content-type": "error",
        "disown-opener": "error",
        "highest-available-document-mode": "error",
        "html-checker": "error",
        "http-cache": "error",
        "http-compression": "error",
        "meta-charset-utf-8": "error",
        "meta-viewport": "error",
        "no-bom": "error",
        "no-disallowed-headers": "error",
        "no-friendly-error-pages": "error",
        "no-html-only-headers": "error",
        "no-http-redirects": "error",
        "no-protocol-relative-urls": "error",
        "no-vulnerable-javascript-libraries": "error",
        "sri": "error",
        "ssllabs": "error",
        "strict-transport-security": "error",
        "validate-set-cookie-header": "error",
        "x-content-type-options": "error"
    },
    "rulesTimeout": 120000
}
