=== webhintio/hint/packages/hint/src/lib/config/config-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Configuration",
    "description": "A configuration file for sonarwhal",
    "type": "object",
    "properties": {
        "connector": {
            "description": "The connector to use to gather information",
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "The name of the connector to use",
                            "type": "string"
                        },
                        "options": {
                            "description": "The options to pass to the connector",
                            "type": "object"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "string"
                }
            ]
        },
        "extends": {
            "description": "Base configuration to use.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "formatters": {
            "description": "The formatter(s) to use for the results",
            "oneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "string"
                }
            ]
        },
        "parsers": {
            "description": "The parsers to be used with the connector to gather information for specific file types",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "hintsTimeout": {
            "description": "Time in milliseconds that a hint has to finish",
            "type": "number"
        },
        "hints": {
            "description": "The hints to validate",
            "anyOf": [
                {
                    "$ref": "#/definitions/hintobject"
                },
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object"
                                    }
                                ],
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "minItems": 1
                }
            ],
            "minItems": 1,
            "uniqueItems": true
        },
        "browserslist": {
            "description": "The browsers supported",
            "anyOf": [
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true
                },
                {
                    "type": "string"
                }
            ]
        },
        "ignoredUrls": {
            "description": "The urls to ignore by the hints",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "domain": {
                        "type": "string",
                        "description": "Regex for the domain to ignore"
                    },
                    "hints": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "uniqueItems": true
                        }
                    }
                },
                "uniqueItems": true
            }
        }
    },
    "anyOf": [
        {
            "required": [
                "connector",
                "hints"
            ]
        },
        {
            "required": [
                "extends"
            ]
        }
    ],
    "additionalProperties": false,
    "definitions": {
        "errorlevelstring": {
            "type": "string",
            "enum": [
                "off",
                "warning",
                "error"
            ]
        },
        "errorlevelnumber": {
            "type": "number",
            "enum": [
                0,
                1,
                2
            ]
        },
        "hintconfig": {
            "type": "array",
            "items": [
                {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/errorlevelstring"
                        },
                        {
                            "$ref": "#/definitions/errorlevelnumber"
                        }
                    ]
                },
                {
                    "type": "object"
                }
            ],
            "maxItems": 2,
            "minItems": 1,
            "uniqueItems": true
        },
        "hintobject": {
            "type": "object",
            "patternProperties": {
                "^.+$": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/errorlevelstring"
                        },
                        {
                            "$ref": "#/definitions/errorlevelnumber"
                        },
                        {
                            "$ref": "#/definitions/hintconfig"
                        }
                    ]
                }
            },
            "minItems": 1,
            "uniqueItems": true
        }
    }
}

=== webhintio/hint/packages/configuration-all/index.json
{
    "connector": "puppeteer",
    "formatters": [
        "html",
        "summary"
    ],
    "hints": {
        "0": "x-content-type-options",
        "1": "webpack-config/is-installed",
        "2": "webpack-config/is-valid",
        "3": "webpack-config/module-esnext-typescript",
        "4": "webpack-config/modules-false-babel",
        "5": "webpack-config/no-devtool-in-prod",
        "6": "axe/other",
        "7": "axe/parsing",
        "8": "axe/semantics",
        "9": "axe/sensory-and-visual-cues",
        "10": "axe/structure",
        "11": "axe/tables",
        "12": "axe/text-alternatives",
        "13": "axe/time-and-media"
    },
    "hintsTimeout": 120000,
    "parsers": [
        "babel-config",
        "css",
        "html",
        "javascript",
        "jsx",
        "less",
        "manifest",
        "package-json",
        "sass",
        "typescript",
        "typescript-config",
        "webpack-config"
    ]
}

=== webhintio/hint/packages/configuration-progressive-web-apps/index.json
{
    "connector": {
        "name": "jsdom",
        "options": {
            "waitFor": 5000
        }
    },
    "formatters": [
        "html",
        "summary"
    ],
    "hints": {
        "apple-touch-icons": "error",
        "manifest-app-name": "error",
        "manifest-exists": "error",
        "manifest-file-extension": "error",
        "manifest-is-valid": "error"
    },
    "hintsTimeout": 120000,
    "parsers": [
        "manifest"
    ]
}

=== webhintio/hint/packages/configuration-development/index.json
{
    "connector": "local",
    "formatters": [
        "html",
        "summary"
    ],
    "hints": {
        "axe": "error",
        "babel-config/is-valid": "error",
        "disown-opener": "error",
        "highest-available-document-mode": "error",
        "meta-charset-utf-8": "error",
        "meta-viewport": "error",
        "no-bom": "error",
        "no-protocol-relative-urls": "error",
        "typescript-config/consistent-casing": "error",
        "typescript-config/import-helpers": "error",
        "typescript-config/is-valid": "error",
        "typescript-config/no-comments": "error",
        "typescript-config/strict": "error",
        "typescript-config/target": "error",
        "webpack-config/is-installed": "error",
        "webpack-config/is-valid": "error",
        "webpack-config/module-esnext-typescript": "error",
        "webpack-config/modules/false-babel": "error",
        "webpack-config/no-devtool-in-prod": "error"
    },
    "hintsTimeout": 10000,
    "parsers": [
        "babel-config",
        "html",
        "typescript-config",
        "webpack-config"
    ]
}
